# Frozen Lake Q Learning

In [130]:
import numpy as np
import gym
import random 
import time
from IPython.display import clear_output

In [131]:
# Create an environment

env = gym.make("FrozenLake-v1", render_mode="ansi")

In [132]:
# Constructing a Q-table and initializing the values to 0

action_space_size = env.action_space.n  # Columns
state_space_size = env.observation_space.n # Rows

q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [133]:
# Creating up algorithm parameters

num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1  # Alpha
discount_rate = 0.99 # Gamma

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.0001

# TODO: --> Use Exploration_decay_rate as 0.01 and 0.001 after end of this project to test which one is better.

In [134]:
# Implementing the algorithm

reward_all_episodes = []

# Q-Learning algorithm
# This for loop contains everything that happens in a single episode.
for episode in range(num_episodes): 
    state = env.reset()
    if isinstance(state, tuple):  # Handle new Gym versions where reset returns (state, info)
        state = state[0]
    
    done = False
    reward_current_episode = 0
    
    # This for loop contains everything that happens for a single timestamp in each episode.
    for step in range(max_steps_per_episode):
        
        # Exploration-exploitation trade-off
        exploration_rate_threshold  = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done,terminated, info = env.step(action)
        
        
        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        
        state = new_state
        reward_current_episode += reward
        
        if done == True:
            break
        
        
    # Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    reward_all_episodes.append(reward_current_episode)
    
    
# Calculate and print the average reward per thousand episodes
reward_per_thousand_episodes = np.split(np.array(reward_all_episodes),num_episodes/1000)
count = 1000
print('*********Average reward per thousand episodes********')
for r in reward_per_thousand_episodes:
    print(count,": ",str(sum(r/1000)))
    count +=1000
   
   
# print updated Q-table
print("\n\n*********Q-Table**********\n")
print(q_table)     

*********Average reward per thousand episodes********
1000 :  0.014000000000000005
2000 :  0.014000000000000005
3000 :  0.01900000000000001
4000 :  0.03300000000000002
5000 :  0.04100000000000003
6000 :  0.060000000000000046
7000 :  0.06200000000000005
8000 :  0.07500000000000005
9000 :  0.06800000000000005
10000 :  0.09500000000000007


*********Q-Table**********

[[0.54429845 0.53563576 0.53725263 0.52504671]
 [0.41853064 0.40311972 0.3593576  0.49467468]
 [0.45033956 0.44240889 0.42076052 0.45454649]
 [0.34299374 0.32924403 0.31262657 0.4411992 ]
 [0.56060273 0.34599603 0.35615172 0.31442041]
 [0.         0.         0.         0.        ]
 [0.38076935 0.26883874 0.44765201 0.20548114]
 [0.         0.         0.         0.        ]
 [0.38773942 0.40650936 0.45090344 0.63555678]
 [0.43364054 0.67621873 0.4729946  0.4860658 ]
 [0.67785448 0.35077704 0.55734786 0.27791365]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.5252755  0.315473

In [135]:
# Make agent pay frozen lake

for episode in range(3):
    state = env.reset()[0]
    done = False
    if isinstance(state, tuple):
        state = state[0]
    
    state = int(state)  # Ensure state is an integer
    print("************EPISODE ", episode+1, "*************\n\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait = True)
        print(env.render())
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state,reward,done,info, terminated = env.step(action)
        
        if done:
            clear_output(wait=True)
            print(env.render())
            if reward==1:
                print("*******You reached the goal*******")
                time.sleep(3)
            else:
                print("*****You fell through a hole**********")
                time.sleep(3)
            clear_output(wait=True)
            break
        
        state = new_state
    
env.close()

  (Right)
SFFF
FHFH
FFFH
HFFG

